#! /usr/bin/env node
import inquirer from "inquirer";


let randomnum = Math.floor(Math.random() * 10)

const guessnumber = async()=> {


let {guessnum} = await inquirer.prompt([
    {
        name : "guessnum",
        type : "number",
        message : "Guess a number which is generated by the computer between 1 and 10"
    }
])
console.log(guessnum)
if(guessnum <  1 || guessnum > 10){
    console.log("Please choose number between 1 and 10")
    guessnumber()
}
else if(guessnum == randomnum){
    console.log("You have Guess the correct number")
}else if(guessnum !== randomnum){
    console.log("OH sorry You guessed Wrong Number")
    let {chance} = await inquirer.prompt([
        {
            name : "chance",
            type : "list",
            choices: ["Yes", "No"],
            message : "Guess a number which is generated by the computer between 1 and 10"
        }
    ])
    
    if(chance == "Yes"){
        guessnumber()
    }else{
        console.log("Oh you Failed to win")
    }
}else {
    guessnumber()
}

}
guessnumber()


